apiVersion: v1
kind: Service
metadata:
  name:  Serviceformyapp
spec:
  selector:
    app:  myapp
  type:  LoadBalancer
  ports:
  - name:  name-of-the-port
    protocol: TCP
    port:  80
    targetPort:  80